# Generated by Django 2.2.2 on 2019-06-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='user',
        ),
        migrations.AlterField(
            model_name='parking',
            name='reserved',
            field=models.BooleanField(),
        ),
    ]
