# Generated by Django 2.2.2 on 2019-06-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_parking_booked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='booked_by',
            field=models.OneToOneField(on_delete=None, to='api.User'),
        ),
    ]
